//! Core domain model: strands, transcript events, and the `Transcript` structure.

use genepred::genepred::Extras;
use genepred::{GenePred, Strand as GpStrand};

/// A DNA strand. Only `+`/`-` are valid in this pipeline; `.`/`?` are rejected at validation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Strand {
    /// Positive strand (`+`).
    Plus,
    /// Negative strand (`-`).
    Minus,
}

impl Strand {
    /// The single-character BED representation.
    pub fn as_char(self) -> char {
        match self {
            Strand::Plus => '+',
            Strand::Minus => '-',
        }
    }

    /// Convert from a `genepred` strand, returning `None` for unknown strands.
    pub fn from_genepred(s: GpStrand) -> Option<Self> {
        match s {
            GpStrand::Forward => Some(Strand::Plus),
            GpStrand::Reverse => Some(Strand::Minus),
            GpStrand::Unknown => None,
        }
    }
}

impl From<Strand> for GpStrand {
    fn from(s: Strand) -> Self {
        match s {
            Strand::Plus => GpStrand::Forward,
            Strand::Minus => GpStrand::Reverse,
        }
    }
}

/// A splice/truncation event type (spec §4.5).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EventType {
    /// Move an internal donor site into the adjacent intron.
    AlternativeDonor,
    /// Move an internal acceptor site into the adjacent intron.
    AlternativeAcceptor,
    /// Remove one internal exon.
    ExonSkipping,
    /// Merge two exons flanking one intron.
    IntronRetention,
    /// Truncate the 5′ end at an internal exon midpoint.
    FivePrimeTruncation,
}

impl EventType {
    /// All event types, in a fixed order.
    pub const ALL: [EventType; 5] = [
        EventType::AlternativeDonor,
        EventType::AlternativeAcceptor,
        EventType::ExonSkipping,
        EventType::IntronRetention,
        EventType::FivePrimeTruncation,
    ];

    /// The snake_case manifest label.
    pub fn label(self) -> &'static str {
        match self {
            EventType::AlternativeDonor => "alternative_donor",
            EventType::AlternativeAcceptor => "alternative_acceptor",
            EventType::ExonSkipping => "exon_skipping",
            EventType::IntronRetention => "intron_retention",
            EventType::FivePrimeTruncation => "five_prime_truncation",
        }
    }

    /// The short code used in generated transcript IDs.
    pub fn code(self) -> &'static str {
        match self {
            EventType::AlternativeDonor => "AD",
            EventType::AlternativeAcceptor => "AA",
            EventType::ExonSkipping => "ES",
            EventType::IntronRetention => "IR",
            EventType::FivePrimeTruncation => "T5",
        }
    }

    /// Parse the CLI weight key (`donor`, `acceptor`, `skip`, `retention`, `truncation`).
    pub fn from_weight_key(key: &str) -> Option<Self> {
        match key {
            "donor" => Some(EventType::AlternativeDonor),
            "acceptor" => Some(EventType::AlternativeAcceptor),
            "skip" => Some(EventType::ExonSkipping),
            "retention" => Some(EventType::IntronRetention),
            "truncation" => Some(EventType::FivePrimeTruncation),
            _ => None,
        }
    }
}

/// Provenance of a transcript.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Provenance {
    /// Present in the input annotation.
    Original,
    /// Generated by a local splice/truncation event.
    Generated(EventType),
    /// Generated by a two-gene fusion.
    Fusion,
}

/// The two-partner information attached to a fusion transcript.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FusionInfo {
    /// 5′ partner gene id (transcript orientation).
    pub gene_5p: String,
    /// 5′ partner transcript id.
    pub transcript_5p: String,
    /// 3′ partner gene id.
    pub gene_3p: String,
    /// 3′ partner transcript id.
    pub transcript_3p: String,
}

/// A structural key for global deduplication (spec §4.7):
/// chromosome, strand, ordered exon starts, ordered exon ends.
pub type StructuralKey = (String, Strand, Vec<u64>, Vec<u64>);

/// A transcript in internal representation. Exons are absolute, half-open genomic intervals,
/// always sorted ascending and non-overlapping.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Transcript {
    /// Unique transcript identifier.
    pub id: String,
    /// Owning gene identifier (or fusion pseudo-gene for fusions).
    pub gene_id: String,
    /// Chromosome / scaffold name.
    pub chrom: String,
    /// Strand.
    pub strand: Strand,
    /// Sorted, non-overlapping, half-open exon intervals `[start, end)`.
    pub exons: Vec<(u64, u64)>,
    /// Coding-region start (BED `thickStart`).
    pub thick_start: u64,
    /// Coding-region end (BED `thickEnd`).
    pub thick_end: u64,
    /// Provenance.
    pub provenance: Provenance,
    /// The parent transcript for generated events (`None` for originals/fusions).
    pub parent_id: Option<String>,
    /// Fusion partner information (`Some` only for fusions).
    pub fusion: Option<FusionInfo>,
    /// Whether the coding frame is defined (false for fusions).
    pub coding_defined: bool,
    /// Seed of the RNG stream that produced this transcript (global seed for originals).
    pub seed: u64,
}

impl Transcript {
    /// Genomic transcription start (0-based) = first exon start.
    pub fn chrom_start(&self) -> u64 {
        self.exons.first().map(|e| e.0).unwrap_or(0)
    }

    /// Genomic transcription end = last exon end.
    pub fn chrom_end(&self) -> u64 {
        self.exons.last().map(|e| e.1).unwrap_or(0)
    }

    /// Number of exons.
    pub fn exon_count(&self) -> usize {
        self.exons.len()
    }

    /// Total exonic (spliced) length = sum of block sizes.
    pub fn transcript_length(&self) -> u64 {
        self.exons.iter().map(|(s, e)| e.saturating_sub(*s)).sum()
    }

    /// Introns as `[start, end)` intervals between consecutive exons.
    pub fn introns(&self) -> Vec<(u64, u64)> {
        self.exons.windows(2).map(|w| (w[0].1, w[1].0)).collect()
    }

    /// The structural key used for deduplication.
    pub fn structural_key(&self) -> StructuralKey {
        let starts = self.exons.iter().map(|e| e.0).collect();
        let ends = self.exons.iter().map(|e| e.1).collect();
        (self.chrom.clone(), self.strand, starts, ends)
    }

    /// Validate that exon blocks are sorted, positive-length, and non-overlapping.
    ///
    /// Returns a description of the first problem found, or `Ok(())`.
    pub fn validate_blocks(&self) -> std::result::Result<(), String> {
        if self.exons.is_empty() {
            return Err("transcript has no exon blocks".to_string());
        }
        let mut prev_end: Option<u64> = None;
        for (i, &(s, e)) in self.exons.iter().enumerate() {
            if e <= s {
                return Err(format!(
                    "block {i} has non-positive length (start={s}, end={e})"
                ));
            }
            if let Some(pe) = prev_end {
                if s < pe {
                    return Err(format!(
                        "block {i} (start={s}) overlaps or precedes previous block end {pe}"
                    ));
                }
                if s == pe {
                    return Err(format!(
                        "block {i} (start={s}) abuts previous block end {pe} (blocks must be separated by a positive intron)"
                    ));
                }
            }
            prev_end = Some(e);
        }
        Ok(())
    }

    /// Convert to a `genepred::GenePred` for BED12 output.
    pub fn to_genepred(&self) -> GenePred {
        let starts: Vec<u64> = self.exons.iter().map(|e| e.0).collect();
        let ends: Vec<u64> = self.exons.iter().map(|e| e.1).collect();
        let mut g = GenePred::from_coords(
            self.chrom.clone().into_bytes(),
            self.chrom_start(),
            self.chrom_end(),
            Extras::new(),
        );
        g.set_name(Some(self.id.clone().into_bytes()));
        g.set_strand(Some(self.strand.into()));
        g.set_thick_start(Some(self.thick_start));
        g.set_thick_end(Some(self.thick_end));
        g.set_block_count(Some(self.exons.len() as u32));
        g.set_block_starts(Some(starts));
        g.set_block_ends(Some(ends));
        g
    }
}

/// Canonical sort key for deterministic output ordering (spec §4.8):
/// chromosome, chromStart, chromEnd, strand, transcript_id.
pub fn canonical_sort(transcripts: &mut [Transcript]) {
    transcripts.sort_by(|a, b| {
        a.chrom
            .cmp(&b.chrom)
            .then(a.chrom_start().cmp(&b.chrom_start()))
            .then(a.chrom_end().cmp(&b.chrom_end()))
            .then(a.strand.as_char().cmp(&b.strand.as_char()))
            .then(a.id.cmp(&b.id))
    });
}
